<template>
  <div class="flex justify-center mt-16">
    <div
      class="
        bg-yellow-500
        h-40
        w-40
        rounded-2xl
        flex
        items-center
        justify-center
        mx-3
      "
    >
      1
    </div>
    <div
      class="
        bg-yellow-500
        h-40
        w-40
        rounded-2xl
        flex
        items-center
        justify-center
        mx-3
      "
    >
      1
    </div>
    <div
      class="
        bg-yellow-500
        h-40
        w-40
        rounded-2xl
        flex
        items-center
        justify-center
        mx-3
      "
    >
      1
    </div>
  </div>
</template>